Community Standards
Astrabit-ST/Luminol pull request #63
Opened 2023-11-22 09:59 UTC by Speak2Erase

As Luminol is getting more attention from people outside of Astrabit, it's more important than ever to have some solid guidelines for how people can contribute to the project. I've had a couple of people reach out to me about helping the project, and we've even had someone make massive contributions to Luminol! (white-axe)

I've added some basic contribution guidelines as well as clean up the readme. I haven't outlined any branch/release guidelines yet, as I felt they weren't quite necessary. We're at least a few months off from having an actual release, which is when we'd need those. 

I also went ahead and added a CODEOWNERS file so reviews are automatically requested whenever someone makes a pull request.

2023-11-22 14:54 UTC, white-axe approved these changes

2023-11-23 06:25 UTC, callistoAshley commented on .github/ISSUE_TEMPLATE/compiler-error.md
This file is fine, but the name doesn't follow the snake_casing convention like the rest of the markdown files.

2023-11-23 06:26 UTC, somedevfox requested changes

2023-11-23 06:26 UTC, somedevfox commented on CONTRIBUTING.md
It's not stated that we use conventional commit style (i.e. `feat: implement new api`). I feel like this should be clarified.

2023-11-23 06:38 UTC, callistoAshley approved these changes

2023-11-23 06:42 UTC, somedevfox approved these changes

2023-11-23 06:44 UTC, merged